name: encura
description: Your Pocket AI Curator.
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.6.14
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  geolocator: ^13.0.1
  google_fonts: ^6.1.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  cached_network_image: ^3.4.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#121212" # 背景色（チャコールグレー）
  image: "assets/icon.png" # アプリアイコンと同じ画像を使用
  android_12:
    image: "assets/icon.png"
    color: "#121212"
  ios: true
  android: true
  
flutter:
  uses-material-design: true

  assets:
    - .env
    
