name: encura
description: Your Pocket AI Curator.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.6.14
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  geolocator: ^13.0.1
  google_fonts: ^6.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    
